//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FolioConsoleUI.FolioService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FolioService.IFolioService")]
    public interface IFolioService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolioService/GetFolioStatus", ReplyAction="http://tempuri.org/IFolioService/GetFolioStatusResponse")]
        FolioLibrary.Data.FolioDTO GetFolioStatus(int folio, int broker);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFolioService/GetFolioStatus", ReplyAction="http://tempuri.org/IFolioService/GetFolioStatusResponse")]
        System.Threading.Tasks.Task<FolioLibrary.Data.FolioDTO> GetFolioStatusAsync(int folio, int broker);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFolioServiceChannel : FolioConsoleUI.FolioService.IFolioService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FolioServiceClient : System.ServiceModel.ClientBase<FolioConsoleUI.FolioService.IFolioService>, FolioConsoleUI.FolioService.IFolioService {
        
        public FolioServiceClient() {
        }
        
        public FolioServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FolioServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolioServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FolioServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FolioLibrary.Data.FolioDTO GetFolioStatus(int folio, int broker) {
            return base.Channel.GetFolioStatus(folio, broker);
        }
        
        public System.Threading.Tasks.Task<FolioLibrary.Data.FolioDTO> GetFolioStatusAsync(int folio, int broker) {
            return base.Channel.GetFolioStatusAsync(folio, broker);
        }
    }
}
